services:
  - type: web
    name: docudant
    env: python
    buildCommand: |
      apt-get update && \
      apt-get install -y tesseract-ocr && \
      pip install --upgrade pip && \
      pip install -r requirements.txt
    startCommand: bash start.sh
    envVars:
      - key: OPENAI_API_KEY
        sync: false
