services:
  - type: web
    name: docudant
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: streamlit run app.py --server.port 10000
envVars:
  - key: OPENAI_API_KEY
    sync: false
